AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: https://github.com/m-mizutani/gsuite-log-exporter
Parameters:
  DlqTopicName:
    Type: String
    Default: ""
  LambdaRoleArn:
    Type: String
    Default: ""

Conditions:
  LambdaRoleRequired:
    Fn::Equals: [ { Ref: LambdaRoleArn }, "" ]
  IsDefaultDLQName:
    Fn::Equals: [ { Ref: DlqTopicName }, "" ]

Resources:
  # --------------------------------------------------------
  # Lambda functions
  Main:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: build
      Handler: main
      Timeout: 60
      Role:
        Fn::If: [ LambdaRoleRequired, {"Fn::GetAtt": LambdaRole.Arn}, {Ref: LambdaRoleArn} ]
      DeadLetterQueue:
        Type: SNS
        TargetArn:
          Ref: DLQ
      MemorySize: 1024
      Events:
        Test:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGW

  ApiGW:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  DLQ:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::If:
          - IsDefaultDLQName
          - {"Fn::Sub": [ "sam-task-kitchen-dlq-${StackName}", { StackName: { "Ref": "AWS::StackName" } } ] }
          - {"Ref": DlqTopicName}

  # --------------------------------------------------------
  # IAM Roles
  LambdaRole:
    Type: AWS::IAM::Role
    Condition: LambdaRoleRequired
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["lambda.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "PublishDLQ"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - Ref: DLQ
